---
# yaml-language-server: $schema=https://json.schemastore.org/kustomization
apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
resources:
  - ./namespace.yaml
  - ./crunchy-postgres
  - ./valkey
  - ./pgweb
  - ./dragonfly
  - ../../../shared/templates/flux
transformers:
  - |-
    apiVersion: builtin
    kind: NamespaceTransformer
    metadata:
      name: not-used
      namespace: databases
    unsetOnly: true
