---
apiVersion: k8s.cni.cncf.io/v1
kind: NetworkAttachmentDefinition
metadata:
  name: multus-srv
  namespace: kube-system
spec:
  config: |-
    {
      "cniVersion": "0.3.1",
      "name": "multus-srv",
      "plugins": [
        {
          "type": "macvlan",
          "master": "eth1.10",
          "mode": "bridge",
          "capabilities": {
            "ips": true
          },
          "ipam": {
            "type": "static",
            "routes": [
              { "dst": "192.168.10.0/24", "gw": "192.168.10.1" }
            ]
          }
        }
      ]
    }
