---
# yaml-language-server: $schema=https://kubernetes-schemas.plexuz.xyz/gitrepository_v1.json
apiVersion: source.toolkit.fluxcd.io/v1
kind: GitRepository
metadata:
  name: dextek
  namespace: flux-system
spec:
  interval: 30m
  ref:
    branch: main
  url: ssh://git@github.com/krezh/dextek
  secretRef:
    name: github-deploy-key
  ignore: |
    # exclude all
    /*
    # include gitops dirs
    !/clusters/dextek
---
# yaml-language-server: $schema=https://raw.githubusercontent.com/fluxcd-community/flux2-schemas/main/kustomization-kustomize-v1.json
apiVersion: kustomize.toolkit.fluxcd.io/v1
kind: Kustomization
metadata:
  name: cluster
  namespace: flux-system
spec:
  interval: 30m
  path: ./clusters/dextek/flux
  prune: true
  wait: false
  sourceRef:
    kind: GitRepository
    name: dextek
  decryption:
    provider: sops
    secretRef:
      name: sops-age
  dependsOn:
    - name: flux
  postBuild:
    substituteFrom:
      - kind: ConfigMap
        name: cluster-settings
        optional: false
      - kind: Secret
        name: cluster-secrets
        optional: false
