apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
namespace: flux-system
resources:
  - ./actions-runner.yaml
  - ./angelnu.yaml
  - ./authentik.yaml
  - ./backube.yaml
  - ./bitnami.yaml
  - ./bjw-s.yaml
  - ./cilium.yaml
  - ./cloudnative-pg.yaml
  - ./csi-driver-nfs.yaml
  - ./democratic-csi.yaml
  - ./descheduler.yaml
  - ./external-dns.yaml
  - ./external-secrets.yaml
  - ./fairwinds.yaml
  - ./grafana.yaml
  - ./ingress-nginx.yaml
  - ./itzg.yaml
  - ./jetstack.yaml
  - ./k8s-gateway.yaml
  - ./k8tz.yaml
  - ./kyverno.yaml
  - ./metrics-server.yaml
  - ./node-feature-discovery.yaml
  - ./piraeus.yaml
  - ./prometheus-community.yaml
  - ./rook-release.yaml
  - ./staketer.yaml
  - ./tf-controller.yaml
  - ./vector.yaml
  - ./zitadel.yaml
  - ./dragonfly.yaml
  - ./postfinance.yaml
  - ./deliveryhero.yaml
  - ./dbman.yaml
  - ./spegel.yaml
  - ./tailscale.yaml
  - ./ananace.yaml
