---
# yaml-language-server: $schema=https://kubernetes-schemas.plexuz.xyz/external-secrets.io/externalsecret_v1.json
apiVersion: external-secrets.io/v1
kind: ExternalSecret
metadata:
  name: grafana
spec:
  refreshInterval: 1h
  secretStoreRef:
    kind: ClusterSecretStore
    name: infisical
  target:
    name: grafana-secret
    creationPolicy: Owner
    template:
      data:
        # Authentik
        GF_AUTH_GENERIC_OAUTH_CLIENT_ID: "{{ .GRAFANA_OAUTH_CLIENT_ID }}"
        GF_AUTH_GENERIC_OAUTH_CLIENT_SECRET: "{{ .GRAFANA_OAUTH_CLIENT_SECRET }}"
        # Admin User
        GF_SECURITY_ADMIN_USER: "{{ .GRAFANA_ADMIN_USER }}"
        GF_SECURITY_ADMIN_PASSWORD: "{{ .GRAFANA_ADMIN_PASS }}"
  dataFrom:
    - extract:
        key: /DexTek/GRAFANA
---
# yaml-language-server: $schema=https://kubernetes-schemas.plexuz.xyz/external-secrets.io/externalsecret_v1.json
apiVersion: external-secrets.io/v1
kind: ExternalSecret
metadata:
  name: grafana-postgres
spec:
  refreshInterval: 5m
  secretStoreRef:
    kind: ClusterSecretStore
    name: crunchy-pgo-secrets
  target:
    name: grafana-postgres-secret
    creationPolicy: Owner
    template:
      data:
        GF_DATABASE_SSL_MODE: disable
        GF_DATABASE_TYPE: postgres
        GF_DATABASE_NAME: '{{ index . "dbname" }}'
        GF_DATABASE_HOST: '{{ index . "pgbouncer-host" }}'
        GF_DATABASE_USER: '{{ index . "user" }}'
        GF_DATABASE_PASSWORD: '{{ index . "password" }}'
  dataFrom:
    - extract:
        key: postgres-pguser-grafana
