---
# yaml-language-server: $schema=https://json.schemastore.org/kustomization
apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
namespace: monitoring
resources:
  - ./ocirepository.yaml
  - ./helmrelease.yaml
  - ./dashboards
  - ./alertmanagerconfig.yaml
  - ./externalsecret.yaml
  - ./scrapeconfigs.yaml
  - ./dashboard.yaml
